// =============================================================================
//   2D Barcode VCL Components
//
//   Author: HAN JING YU
//   E-Mail: support@han-soft.com
//   WebURL: http://www.han-soft.com
//   Copyright (C) Han-soft Corporation. All rights reserved.
// =============================================================================
//   $Id: barcodes_use.inc 2300 2015-03-14 16:20:08Z hanjy $
// =============================================================================

pAztecCode,
pAztecRunes,
pCode16K,
pDataMatrix,
pDataMatrixEcc200,
{$IFDEF INCLUDE_EZCODE_SYMBOLOGY} pEZcode, {$ENDIF}
pMaxiCode,
pMicroPDF417,
pMicroQRcode,
pPDF417,
pQRcode,
pHanXinCode,
pSCCom,
pGridMatrix,
pCompactMatrix,
pRss14,
pRssExpanded,
pRssLimited,
pCCCustom,
pCCA,
pCCB,
pCCC,
pPDF417Custom,
pUPCA,
pUPCE,
pUPCE0,
pUPCE1,
pEAN8,
pEAN13,
pEAN128,
